apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ros-robot1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ros-robot1
  template:
    metadata:
      labels:
        app: react-ros-robot1
    spec:
      containers:
        - name: react-ros-robot1
          image: vishal6363/react-ros-robot1:latest
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80
            - name: backend
              containerPort: 5000
            - name: rosbridge
              containerPort: 9090
          env:
            - name: ROS_MASTER_URI
              value: "http://localhost:11311"
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              source /opt/ros/noetic/setup.bash

              echo "Preparing React frontend..."
              node /app/frontend-server.js &

              echo "Starting ROS master..."
              roscore &
              sleep 5

              echo "Starting ROS bridge..."
              roslaunch rosbridge_server rosbridge_websocket.launch &

              echo "Starting backend..."
              cd /app/backend
              exec npm start
