apiVersion: v1
kind: Service
metadata:
  name: react-ros-robot1
spec:
  type: NodePort

  selector:
    app: react-ros-robot1

  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080

    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

    - name: rosbridge
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
